In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [13]:
sent_length=8
sent_length = 8
one_hot_repr = [one_hot(words, voc_size) for words in sent]
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)
print(embedded_docs)

[[   0    0    0    0 3964 5039 9438 2955]
 [   0    0    0    0 3964 5039 9438 3461]
 [   0    0    0    0 3964 3593 9438 4637]
 [   0    0    0 8028 3864 7879 2132 6033]
 [   0    0    0 8028 3864 7879 2132 8301]
 [   0    0    0 7600 3964 3987 9438  176]
 [   0    0    0    0 6551 1419  170 2132]]
[[   0    0    0    0 3964 5039 9438 2955]
 [   0    0    0    0 3964 5039 9438 3461]
 [   0    0    0    0 3964 3593 9438 4637]
 [   0    0    0 8028 3864 7879 2132 6033]
 [   0    0    0 8028 3864 7879 2132 8301]
 [   0    0    0 7600 3964 3987 9438  176]
 [   0    0    0    0 6551 1419  170 2132]]


In [ ]:
## feature representation
dim=10

In [14]:
model=Sequential()
embedding_dim = globals().get('dim', 10)
model.add(Embedding(voc_size, embedding_dim, input_length=sent_length))
model.compile('adam','mse')

In [15]:
# build the model before calling summary
model.build(input_shape=(None, sent_length))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.predict(embedded_docs)

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 3964, 5039, 9438, 2955])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 91ms/step


array([[ 3.7318733e-02,  1.1163820e-02, -1.0181271e-02, -4.2209055e-02,
         3.3177435e-05, -3.2645367e-02,  3.7327599e-02, -4.0313948e-02,
        -1.2005936e-02, -3.9044607e-02],
       [ 3.7318733e-02,  1.1163820e-02, -1.0181271e-02, -4.2209055e-02,
         3.3177435e-05, -3.2645367e-02,  3.7327599e-02, -4.0313948e-02,
        -1.2005936e-02, -3.9044607e-02],
       [ 3.7318733e-02,  1.1163820e-02, -1.0181271e-02, -4.2209055e-02,
         3.3177435e-05, -3.2645367e-02,  3.7327599e-02, -4.0313948e-02,
        -1.2005936e-02, -3.9044607e-02],
       [ 3.7318733e-02,  1.1163820e-02, -1.0181271e-02, -4.2209055e-02,
         3.3177435e-05, -3.2645367e-02,  3.7327599e-02, -4.0313948e-02,
        -1.2005936e-02, -3.9044607e-02],
       [ 4.1725960e-02,  1.5207980e-02,  4.3945756e-02,  4.5122616e-03,
         4.9298182e-03,  2.1266453e-03, -3.3888541e-02,  2.4294887e-02,
        -1.4841460e-02, -3.3659101e-02],
       [-1.0599863e-02, -8.7428689e-03, -4.5732941e-02,  3.2353353e-02,
   